[package]
name = "steshaw/idris-elba-example"
version = "0.1.0"
description = "An example of Idris using the elba package system"
homepage = "https://github.com/steshaw/idris-elba-example"
repository = "https://github.com/steshaw/idris-elba-example"
authors = ["Steven Shaw <steven@steshaw.org>"]
readme = "README.org"
licence = "MIT"
licence-file = "LICENCE"
keywords = ["example"]

[dependencies]

[[targets.bin]]
path = "src"
name = "idris-elba-example"
main = "Main"
